title: minimal-jekyll-ghp
email: me@bryanculver.com
description: A fork of @orderlist's Minimal theme, built for GitHub Pages + Jekyll

# HEADS UP: Change these for your use
baseurl: "/minimal-jekyll-ghp/" 
url: "https://bryanculver.github.io/minimal-jekyll-ghp/"


# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - /tmp/
  - config.ru


# Development Parameter for Puma 
destination: "public/minimal-jekyll-ghp"
